Remove implicit dependency on wslvar binary (#198)
sindresorhus/open pull request #204
Opened 2020-10-23 13:39 UTC by tim-stasse

Fixes #198

2020-10-23 15:39 UTC, tim-stasse commented
I believe this would make [200](https://github.com/sindresorhus/open/pull/200) redundant (if accepted).

2020-11-02 15:14 UTC, sindresorhus requested changes

2020-11-02 15:14 UTC, sindresorhus commented on index.js
> +		const {stdout} = await pExecFile('awk', [
Use JS for the parsing instead of `awk`.

2020-11-02 15:14 UTC, sindresorhus commented on index.js
> +		for (const path of paths) {
This can be done concurrently using `Promise.all`.

2020-11-02 15:14 UTC, sindresorhus commented
Can you describe your changes and why they're required?

2020-12-16 20:52 UTC, jonaskuske requested changes
Since this already adds a detection for `wslAutoMountRoot`, you could use that as well for the check on line 125 instead of hardcoding `/mnt/` – that'd make my PR (#210) unnecessary :)

2021-01-07 06:38 UTC, sindresorhus commented
@tim-stasse Friendly bump :)

2021-01-29 12:39 UTC, anaisbetts commented
@sindresorhus I think I can explain - `wslvar` is not a built-in component, it's optional software that many people don't have. While Powershell is guaranteed to exist, `wslvar` is very much not. fwiw, this bug breaks popular software such as Storybook on WSL because open fails

2021-01-30 14:33 UTC, closed without merging