Feature/new window option
sindresorhus/open pull request #206
Opened 2020-11-30 18:56 UTC by jebrii

Very light feature add here. Added an option for opening an application in a new window. This is useful for when the application is already open.

For example, if attempting to open an incognito window in Google Chrome (see #41 ), the proper command in a Mac OS terminal would be:

`open -n -a "Google Chrome" "$url" --args --incognito`

This should solve #41 by allowing users to use this tool to execute that command.

2020-12-10 08:55 UTC, MortenGregersen commented
It looks like indention is broken on the lines added.

2020-12-11 04:42 UTC, jebrii commented
> It looks like indention is broken on the lines added.

Thanks for bringing this to my attention!

2020-12-20 08:15 UTC, sindresorhus requested changes

2020-12-20 08:15 UTC, sindresorhus commented on index.d.ts
> +		Open the specified url in a new window. This is useful when the app is expected to already be open.
`open` doesn't only open URLs. Also `url` => `URL`.

2020-12-20 08:15 UTC, sindresorhus commented on index.js
> +			cliArguments.push('-n');
Use the long-flag.

2020-12-20 08:15 UTC, sindresorhus commented on index.js
> +		}
Are you sure moving it here is correct? I think the `target` (https://github.com/sindresorhus/open/pull/206/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R155) is order dependent.

2020-12-20 08:15 UTC, sindresorhus commented on package.json
> +		"child_process": "^1.0.2",
This is incorrect.

2020-12-20 08:15 UTC, sindresorhus commented on index.d.ts
> +
Mention your specific use-case of opening incognito mode.

2021-03-07 11:18 UTC, closed without merging