Add openApp api to open an application
sindresorhus/open pull request #263
Opened 2021-10-05 15:13 UTC by Kudo

`open` is good to facilitate cross platform opening. sometimes i just want to open an application without specifying url or file target. the concept is something like `open(null, { app: { name: open.apps.chrome }});`. this pr just introduces an `openApp` api. please help to review if the concept makes sense.

2021-10-06 06:42 UTC, sindresorhus requested changes

2021-10-06 06:42 UTC, sindresorhus commented on index.js
> +const _openImpl = async options => {
```suggestion
const baseOpen = async options => {
```

2021-10-06 06:42 UTC, sindresorhus commented on index.d.ts
> +	openApp: (name: string, appArguments?: string[], options?: open.Options) => Promise<ChildProcess>;
It should not allow the `app` option. You can use the `Omit` helper for this.

2021-10-06 06:42 UTC, sindresorhus commented on index.d.ts
> +	Open an application. Cross-platform.
```suggestion
	Open an app. Cross-platform.
```

Use the word `app` in other places too.

2021-10-06 06:42 UTC, sindresorhus commented on index.d.ts
> +	There is a caveat for [double-quotes on Windows](https://github.com/sindresorhus/open#double-quotes-on-windows) where all double-quotes are stripped from the `target`.
Not relevant to this method.

2021-10-06 06:42 UTC, sindresorhus commented on readme.md
> +// Open app
```suggestion
// Open an app
```

2021-10-06 06:42 UTC, sindresorhus commented on readme.md
> +// Open app with arguments
```suggestion
// Open an app with arguments
```

2021-10-06 06:42 UTC, sindresorhus commented on readme.md
> +
Should describe what it does.

2021-10-06 06:42 UTC, sindresorhus commented on readme.md
> +### open.openApp(name, appArguments?, options?)
I would prefer the `appArguments` to be in options.

2021-10-06 06:42 UTC, sindresorhus commented on readme.md
> +
These should include `Type` like the other documented parameters and options.

2021-10-06 17:25 UTC, Kudo commented
thanks @sindresorhus. these review comments are neat and i should update all. please take a look when you get a chance.

2021-10-07 09:32 UTC, sindresorhus commented on index.d.ts
> +		Optional arguments to open.
This description is not really correct.
```suggestion
		Arguments passed to the app.
```

2021-10-07 09:33 UTC, sindresorhus commented on index.d.ts
> +		The app `arguments` are app dependent. Check the app's documentation for what arguments it accepts.
```suggestion
		These arguments are app dependent. Check the app's documentation for what arguments it accepts.
```

2021-10-07 09:33 UTC, sindresorhus commented on index.d.ts
> +		 */
```suggestion
		*/
```

2021-10-07 09:33 UTC, sindresorhus commented on index.d.ts
> +		readonly arguments?: string[];
```suggestion
		readonly arguments?: readonly string[];
```

2021-10-07 09:35 UTC, sindresorhus commented on readme.md
> +The options are like the options in [`open`](#options) except to remove `options.app` and add the following options.
```suggestion
Same options as [`open`](#options) except `app` and with the following additions:
```

2021-10-07 09:35 UTC, sindresorhus commented on readme.md
> +Type: `Array<string>`
```suggestion
Type: `string[]`\
```

2021-10-07 09:35 UTC, sindresorhus commented on readme.md
> +
Missing the description from index.d.ts

2021-10-07 09:36 UTC, sindresorhus commented
Can you manually verify that these changes do not break normal usage of `open`?

2021-10-07 15:37 UTC, Kudo commented
i did go through the test cases one by one in macos. there are just two cases with pipe not opening anything. that's same with main branch and `open` does not encode `target` in macos. 
https://github.com/sindresorhus/open/blob/e21e623d459210f899dba34bceea2dfdbb6f3827/test.js#L57-L63

2021-10-07 15:56 UTC, merged